### ISSUE TITLE
这段话中  某一个外容器加高度（.text{height:200px}）能具体点吗。直接给父级元素家

### ISSUE THREAD

**Issue by shmilyxwx** [ximan/flexible.rem#2]
PC端Chrome、Android端Chrome、UC：文字过多时（去掉demo中html注释），文字大小会默认加大24px（0.24rem变成36px；0.28rem变成38px）。解决方案：某一个外容器加高度（.text{height:200px}）

**Comment by ximan** [comment]
https://segmentfault.com/q/1010000002505938
希望可以帮到你
